services:
  mage:
    image: mageai/mageai:0.9.74
    container_name: magic
    depends_on:
      - postgres
    command: mage start --port ${MAGE_PORT} --host 0.0.0.0 mage_project
    env_file:
      - .env
    environment:
      ENV: dev
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PG_HOST_PORT: ${PG_HOST_PORT}
    ports:
      - 6789:6789
    volumes:
      - ./mage:/home/src/
      - ./dataset_inmet:/home/src/datasets
    restart: on-failure:5

  postgres:
    image: postgres:17.0
    restart: on-failure
    container_name: postgres-magic
    # build:
    #   context: ./db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_HOST_PORT}:5432"
    
  dev_jupyter:
    #image: jupyter_dev
    container_name: dev-jupyter
    build:
      context: ./jupyter
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${PORTA_JUPYTER}:${PORTA_JUPYTER}"
    volumes:
      - ./jupyter:/home
      - ./dataset_inmet:/home/datasets

  streamlit:
    container_name: streamlit
    build:
      context: ./streamlit
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${ST_APP_PORT}:${ST_APP_PORT}"
    volumes:
      - ./streamlit:/home

  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./fastapi:/home